@host = http://localhost:5248
@token = <COLE-AQUI-O-TOKEN-DA-ALICE>

### Health Check

GET {{host}}/api/health
Accept: application/json

###

### Login - Alice

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "Alice123!"
}

###

### Profile - sem JWT

GET {{host}}/api/profile
Accept: application/json

###

### Profile - Alice autenticada

GET {{host}}/api/profile
Accept: application/json
Authorization: Bearer {{token}}

###

## --------------- OWASP API1 - Broken Object Level Authorization --------------- ##

### BOLA - acesso legítimo da Alice ao próprio pedido

GET {{host}}/api/vulnerable/orders/1
Accept: application/json
Authorization: Bearer {{token}}

###

### BOLA - Alice tentando acessar pedido do Bob

GET {{host}}/api/vulnerable/orders/3
Accept: application/json
Authorization: Bearer {{token}}

###

### BOLA corrigido - Alice acessa o próprio pedido

GET {{host}}/api/secure/orders/1
Accept: application/json
Authorization: Bearer {{token}}

###

### BOLA corrigido - Alice tenta acessar pedido do Bob

GET {{host}}/api/secure/orders/3
Accept: application/json
Authorization: Bearer {{token}}

###

## --------------- OWASP API2 - Broken Authentication --------------- ##

### API2 - Vulnerable Authentication - Attempt 1

POST {{host}}/api/vulnerable/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "wrong-password-1"
}

###

### API2 - Vulnerable Authentication - Attempt 2

POST {{host}}/api/vulnerable/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "wrong-password-2"
}

###

### API2 - Vulnerable Authentication - Attempt 3

POST {{host}}/api/vulnerable/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "wrong-password-3"
}

###

### API2 - Vulnerable Authentication - Attempt 4

POST {{host}}/api/vulnerable/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "wrong-password-4"
}

###

### API2 - Secure Authentication - Attempt 1

POST {{host}}/api/secure/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "wrong-password-1"
}

###

### API2 - Secure Authentication - Attempt 2

POST {{host}}/api/secure/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "wrong-password-2"
}

###

### API2 - Secure Authentication - Attempt 3

POST {{host}}/api/secure/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "wrong-password-3"
}

###

### API2 - Secure Authentication - Attempt 4

POST {{host}}/api/secure/auth/login
Content-Type: application/json

{
  "email": "alice@murayama.local",
  "password": "wrong-password-4"
}

###